/* ==========================================================================
   CrickDesk – Share & Export Module (js/share.js)
   Renders into #page-share
   ========================================================================== */

window.Share = (() => {
  // ── Helpers ────────────────────────────────────────────────────────────
  const Data = () => window.CrickDeskData;
  const Utils = () => window.CrickDeskUtils;

  // ── Canvas Utility: Rounded Rect ──────────────────────────────────────
  function roundRect(ctx, x, y, w, h, r) {
    if (w < 0) w = 0;
    if (h < 0) h = 0;
    r = Math.min(r, w / 2, h / 2);
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.lineTo(x + w - r, y);
    ctx.arcTo(x + w, y, x + w, y + r, r);
    ctx.lineTo(x + w, y + h - r);
    ctx.arcTo(x + w, y + h, x + w - r, y + h, r);
    ctx.lineTo(x + r, y + h);
    ctx.arcTo(x, y + h, x, y + h - r, r);
    ctx.lineTo(x, y + r);
    ctx.arcTo(x, y, x + r, y, r);
    ctx.closePath();
  }

  function downloadCanvas(canvas, filename) {
    const link = document.createElement('a');
    link.download = filename;
    link.href = canvas.toDataURL('image/png');
    link.click();
  }

  function drawDarkBg(ctx, w, h) {
    const grad = ctx.createLinearGradient(0, 0, w, h);
    grad.addColorStop(0, '#0a0e1a');
    grad.addColorStop(1, '#111827');
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, w, h);
  }

  function drawBrandFooter(ctx, w, h) {
    ctx.fillStyle = 'rgba(255,255,255,0.15)';
    ctx.font = '500 11px Inter, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('Generated by CrickDesk', w / 2, h - 14);
  }

  // ══════════════════════════════════════════════════════════════════════
  //  GENERATE: Points Table Image
  // ══════════════════════════════════════════════════════════════════════

  function generatePointsTable() {
    const teams = Data().getTeams();
    const matches = Data().getMatches().filter(m => m.status === 'completed');
    const tournament = Data().getTournament();

    // Build standings
    const standings = {};
    teams.forEach(t => {
      standings[t.id] = { team: t, played: 0, won: 0, lost: 0, tied: 0, nr: 0, points: 0, nrr: 0, runsFor: 0, ballsFor: 0, runsAgainst: 0, ballsAgainst: 0 };
    });

    const pts = tournament.pointsSystem || { win: 2, loss: 0, tie: 1, nr: 1 };

    matches.forEach(m => {
      const s1 = standings[m.team1Id];
      const s2 = standings[m.team2Id];
      if (!s1 || !s2) return;
      s1.played++;
      s2.played++;

      if (m.innings) {
        m.innings.forEach(inn => {
          const s = standings[inn.battingTeamId];
          const opp = inn.battingTeamId === m.team1Id ? standings[m.team2Id] : standings[m.team1Id];
          if (s) { s.runsFor += inn.totalRuns || 0; s.ballsFor += inn.totalBalls || 0; }
          if (opp) { opp.runsAgainst += inn.totalRuns || 0; opp.ballsAgainst += inn.totalBalls || 0; }
        });
      }

      const result = (m.result || '').toLowerCase();
      if (m.status === 'no-result' || result.includes('no result')) {
        s1.nr++; s2.nr++; s1.points += pts.nr; s2.points += pts.nr;
      } else if (m.status === 'tied' || result.includes('tie')) {
        s1.tied++; s2.tied++; s1.points += pts.tie; s2.points += pts.tie;
      } else {
        const t1 = Data().getTeam(m.team1Id);
        const t2 = Data().getTeam(m.team2Id);
        if (m.result && t1 && m.result.includes(t1.name)) {
          s1.won++; s2.lost++; s1.points += pts.win; s2.points += pts.loss;
        } else if (m.result && t2 && m.result.includes(t2.name)) {
          s2.won++; s1.lost++; s2.points += pts.win; s1.points += pts.loss;
        }
      }
    });

    // Calculate NRR
    Object.values(standings).forEach(s => {
      const forRate = s.ballsFor > 0 ? (s.runsFor / s.ballsFor) * 6 : 0;
      const againstRate = s.ballsAgainst > 0 ? (s.runsAgainst / s.ballsAgainst) * 6 : 0;
      s.nrr = (forRate - againstRate).toFixed(3);
    });

    const sorted = Object.values(standings).sort((a, b) => b.points - a.points || parseFloat(b.nrr) - parseFloat(a.nrr));

    // Draw canvas
    const canvas = document.createElement('canvas');
    const W = 1200, H = 630;
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext('2d');

    drawDarkBg(ctx, W, H);

    // Accent line
    const accentGrad = ctx.createLinearGradient(0, 0, W, 0);
    accentGrad.addColorStop(0, '#10b981');
    accentGrad.addColorStop(1, '#059669');
    ctx.fillStyle = accentGrad;
    ctx.fillRect(0, 0, W, 4);

    // Title
    ctx.fillStyle = '#f9fafb';
    ctx.font = '700 28px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(tournament.name || 'CrickDesk Tournament', W / 2, 50);
    ctx.fillStyle = '#9ca3af';
    ctx.font = '400 14px Inter, sans-serif';
    ctx.fillText('Points Table', W / 2, 74);

    // Table header
    const startY = 100;
    const rowH = 48;
    const cols = [
      { label: '#', x: 40, align: 'center' },
      { label: 'Team', x: 120, align: 'left' },
      { label: 'P', x: 420, align: 'center' },
      { label: 'W', x: 500, align: 'center' },
      { label: 'L', x: 570, align: 'center' },
      { label: 'T', x: 640, align: 'center' },
      { label: 'NR', x: 710, align: 'center' },
      { label: 'NRR', x: 810, align: 'center' },
      { label: 'Pts', x: 950, align: 'center' }
    ];

    // Header bg
    ctx.fillStyle = 'rgba(255,255,255,0.05)';
    ctx.fillRect(20, startY, W - 40, rowH);

    ctx.font = '600 13px Inter, sans-serif';
    ctx.fillStyle = '#9ca3af';
    cols.forEach(c => {
      ctx.textAlign = c.align;
      ctx.fillText(c.label, c.x, startY + 30);
    });

    // Rows
    sorted.forEach((s, i) => {
      const y = startY + rowH + i * rowH;

      if (i % 2 === 0) {
        ctx.fillStyle = 'rgba(255,255,255,0.02)';
        ctx.fillRect(20, y, W - 40, rowH);
      }

      // Team color bar
      ctx.fillStyle = s.team.color || '#10b981';
      ctx.fillRect(20, y, 4, rowH);

      ctx.font = '500 14px Inter, sans-serif';
      ctx.fillStyle = '#f9fafb';

      ctx.textAlign = 'center';
      ctx.fillText(i + 1, cols[0].x, y + 30);

      ctx.textAlign = 'left';
      ctx.font = '600 14px Inter, sans-serif';
      ctx.fillText(s.team.name, cols[1].x, y + 30);

      ctx.font = '400 14px Inter, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(s.played, cols[2].x, y + 30);
      ctx.fillStyle = '#10b981';
      ctx.fillText(s.won, cols[3].x, y + 30);
      ctx.fillStyle = '#ef4444';
      ctx.fillText(s.lost, cols[4].x, y + 30);
      ctx.fillStyle = '#f9fafb';
      ctx.fillText(s.tied, cols[5].x, y + 30);
      ctx.fillText(s.nr, cols[6].x, y + 30);

      ctx.fillStyle = parseFloat(s.nrr) >= 0 ? '#10b981' : '#ef4444';
      ctx.fillText(s.nrr > 0 ? '+' + s.nrr : s.nrr, cols[7].x, y + 30);

      ctx.fillStyle = '#fbbf24';
      ctx.font = '700 16px Inter, sans-serif';
      ctx.fillText(s.points, cols[8].x, y + 30);
    });

    drawBrandFooter(ctx, W, H);

    // Preview
    const preview = document.getElementById('share-preview-points');
    if (preview) {
      preview.innerHTML = '';
      const img = document.createElement('img');
      img.src = canvas.toDataURL();
      img.style.cssText = 'width:100%;border-radius:8px;';
      preview.appendChild(img);
    }

    return canvas;
  }

  // ══════════════════════════════════════════════════════════════════════
  //  GENERATE: Match Summary Image
  // ══════════════════════════════════════════════════════════════════════

  function generateMatchSummary(matchId) {
    const match = Data().getMatch(matchId);
    if (!match) return null;
    const t1 = Data().getTeam(match.team1Id);
    const t2 = Data().getTeam(match.team2Id);
    const tournament = Data().getTournament();
    const bpo = tournament.ballsPerOver || 6;

    const canvas = document.createElement('canvas');
    const W = 1200, H = 630;
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext('2d');

    drawDarkBg(ctx, W, H);

    // Top accent
    const accentGrad = ctx.createLinearGradient(0, 0, W, 0);
    accentGrad.addColorStop(0, t1 ? t1.color : '#10b981');
    accentGrad.addColorStop(1, t2 ? t2.color : '#3b82f6');
    ctx.fillStyle = accentGrad;
    ctx.fillRect(0, 0, W, 5);

    // Tournament name
    ctx.fillStyle = '#9ca3af';
    ctx.font = '400 13px Inter, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(tournament.name || 'CrickDesk Tournament', W / 2, 35);

    // Team avatars + names
    const drawTeamAvatar = (x, y, team) => {
      ctx.beginPath();
      ctx.arc(x, y, 35, 0, Math.PI * 2);
      ctx.fillStyle = team ? team.color : '#374151';
      ctx.fill();
      ctx.fillStyle = '#fff';
      ctx.font = '700 18px Outfit, sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      const initials = team ? (team.shortName || team.name.substring(0, 2)).toUpperCase() : '??';
      ctx.fillText(initials, x, y);
      ctx.textBaseline = 'alphabetic';
    };

    drawTeamAvatar(300, 110, t1);
    ctx.fillStyle = '#f9fafb';
    ctx.font = '700 22px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(t1 ? t1.name : 'Team 1', 300, 165);

    // VS
    ctx.fillStyle = '#6b7280';
    ctx.font = '700 20px Outfit, sans-serif';
    ctx.fillText('VS', W / 2, 115);

    drawTeamAvatar(900, 110, t2);
    ctx.fillStyle = '#f9fafb';
    ctx.font = '700 22px Outfit, sans-serif';
    ctx.fillText(t2 ? t2.name : 'Team 2', 900, 165);

    // Scores
    let y = 210;
    if (match.innings) {
      match.innings.forEach((inn, idx) => {
        const team = Data().getTeam(inn.battingTeamId);
        const overs = Utils().formatOvers(inn.totalBalls || 0, bpo);
        const scoreStr = `${inn.totalRuns || 0}/${inn.totalWickets || 0} (${overs} ov)`;
        const x = inn.battingTeamId === match.team1Id ? 300 : 900;
        ctx.fillStyle = team ? team.color : '#10b981';
        ctx.font = '700 32px Outfit, sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText(scoreStr, x, y);
      });
    }

    // Result
    ctx.fillStyle = '#fbbf24';
    ctx.font = '600 18px Inter, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(match.result || '', W / 2, 280);

    // Divider
    ctx.strokeStyle = 'rgba(255,255,255,0.08)';
    ctx.beginPath();
    ctx.moveTo(60, 310);
    ctx.lineTo(W - 60, 310);
    ctx.stroke();

    // Key stats from innings
    let statsY = 350;
    ctx.font = '500 14px Inter, sans-serif';

    if (match.innings) {
      match.innings.forEach(inn => {
        const team = Data().getTeam(inn.battingTeamId);
        const x = inn.battingTeamId === match.team1Id ? 300 : 900;

        if (inn.battingScorecard && inn.battingScorecard.length > 0) {
          const topBat = [...inn.battingScorecard].sort((a, b) => (b.runs || 0) - (a.runs || 0))[0];
          if (topBat) {
            const p = Data().getPlayer(topBat.playerId);
            ctx.fillStyle = '#f9fafb';
            ctx.textAlign = 'center';
            ctx.fillText(`🏏 ${p ? p.name : 'Unknown'}: ${topBat.runs}(${topBat.balls})`, x, statsY);
          }
        }
        if (inn.bowlingScorecard && inn.bowlingScorecard.length > 0) {
          const topBowl = [...inn.bowlingScorecard].sort((a, b) => (b.wickets || 0) - (a.wickets || 0))[0];
          if (topBowl) {
            const p = Data().getPlayer(topBowl.playerId);
            ctx.fillStyle = '#f9fafb';
            ctx.fillText(`🎯 ${p ? p.name : 'Unknown'}: ${topBowl.wickets}/${topBowl.runs}`, x, statsY + 28);
          }
        }
      });
    }

    // Man of the Match
    if (match.manOfMatch) {
      const mom = Data().getPlayer(match.manOfMatch);
      if (mom) {
        ctx.fillStyle = '#fbbf24';
        ctx.font = '600 16px Inter, sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText(`⭐ Man of the Match: ${mom.name}`, W / 2, 460);
      }
    }

    // Date & Venue
    ctx.fillStyle = '#6b7280';
    ctx.font = '400 13px Inter, sans-serif';
    ctx.textAlign = 'center';
    const dateStr = match.date ? Utils().formatDate(match.date) : '';
    const venueStr = match.venue || '';
    ctx.fillText(`${dateStr}${venueStr ? ' • ' + venueStr : ''}`, W / 2, 520);

    // Toss
    if (match.tossWonBy) {
      const tossTeam = Data().getTeam(match.tossWonBy);
      ctx.fillText(`Toss: ${tossTeam ? tossTeam.name : '?'} won, chose to ${match.tossDecision || '?'}`, W / 2, 545);
    }

    drawBrandFooter(ctx, W, H);

    const preview = document.getElementById('share-preview-match');
    if (preview) {
      preview.innerHTML = '';
      const img = document.createElement('img');
      img.src = canvas.toDataURL();
      img.style.cssText = 'width:100%;border-radius:8px;';
      preview.appendChild(img);
    }

    return canvas;
  }

  // ══════════════════════════════════════════════════════════════════════
  //  GENERATE: Fixtures Image
  // ══════════════════════════════════════════════════════════════════════

  function generateFixtures() {
    const upcoming = Data().getMatchesByStatus('upcoming').slice(0, 8);
    const tournament = Data().getTournament();

    const canvas = document.createElement('canvas');
    const W = 1200, H = 630;
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext('2d');

    drawDarkBg(ctx, W, H);

    const accentGrad = ctx.createLinearGradient(0, 0, W, 0);
    accentGrad.addColorStop(0, '#10b981');
    accentGrad.addColorStop(1, '#3b82f6');
    ctx.fillStyle = accentGrad;
    ctx.fillRect(0, 0, W, 4);

    ctx.fillStyle = '#f9fafb';
    ctx.font = '700 26px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(tournament.name || 'CrickDesk Tournament', W / 2, 45);
    ctx.fillStyle = '#9ca3af';
    ctx.font = '400 14px Inter, sans-serif';
    ctx.fillText('Upcoming Fixtures', W / 2, 70);

    if (upcoming.length === 0) {
      ctx.fillStyle = '#6b7280';
      ctx.font = '400 16px Inter, sans-serif';
      ctx.fillText('No upcoming fixtures', W / 2, H / 2);
      drawBrandFooter(ctx, W, H);
      const preview = document.getElementById('share-preview-fixtures');
      if (preview) {
        preview.innerHTML = '';
        const img = document.createElement('img');
        img.src = canvas.toDataURL();
        img.style.cssText = 'width:100%;border-radius:8px;';
        preview.appendChild(img);
      }
      return canvas;
    }

    const cardW = 520, cardH = 60, gap = 12;
    const cols = 2;
    const startY = 100;

    upcoming.forEach((m, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = col === 0 ? 60 : W / 2 + 30;
      const y = startY + row * (cardH + gap);

      roundRect(ctx, x, y, cardW, cardH, 8);
      ctx.fillStyle = 'rgba(255,255,255,0.04)';
      ctx.fill();
      ctx.strokeStyle = 'rgba(255,255,255,0.08)';
      ctx.stroke();

      const t1 = Data().getTeam(m.team1Id);
      const t2 = Data().getTeam(m.team2Id);

      // Team color dots
      ctx.beginPath();
      ctx.arc(x + 20, y + cardH / 2, 6, 0, Math.PI * 2);
      ctx.fillStyle = t1 ? t1.color : '#10b981';
      ctx.fill();

      ctx.fillStyle = '#f9fafb';
      ctx.font = '600 13px Inter, sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText(t1 ? t1.name : 'TBD', x + 34, y + cardH / 2 - 2);

      ctx.fillStyle = '#6b7280';
      ctx.font = '400 12px Inter, sans-serif';
      ctx.fillText('vs', x + 200, y + cardH / 2 - 2);

      ctx.beginPath();
      ctx.arc(x + 230, y + cardH / 2, 6, 0, Math.PI * 2);
      ctx.fillStyle = t2 ? t2.color : '#3b82f6';
      ctx.fill();

      ctx.fillStyle = '#f9fafb';
      ctx.font = '600 13px Inter, sans-serif';
      ctx.fillText(t2 ? t2.name : 'TBD', x + 244, y + cardH / 2 - 2);

      // Date
      ctx.fillStyle = '#9ca3af';
      ctx.font = '400 11px Inter, sans-serif';
      ctx.textAlign = 'right';
      ctx.fillText(m.date ? Utils().formatDate(m.date) : '', x + cardW - 15, y + cardH / 2 + 4);
    });

    drawBrandFooter(ctx, W, H);

    const preview = document.getElementById('share-preview-fixtures');
    if (preview) {
      preview.innerHTML = '';
      const img = document.createElement('img');
      img.src = canvas.toDataURL();
      img.style.cssText = 'width:100%;border-radius:8px;';
      preview.appendChild(img);
    }

    return canvas;
  }

  // ══════════════════════════════════════════════════════════════════════
  //  GENERATE: Team Squad Image
  // ══════════════════════════════════════════════════════════════════════

  function generateTeamSquad(teamId) {
    const team = Data().getTeam(teamId);
    if (!team) return null;
    const players = Data().getPlayersByTeam(teamId);
    const tournament = Data().getTournament();

    const canvas = document.createElement('canvas');
    const W = 600, H = 800;
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext('2d');

    drawDarkBg(ctx, W, H);

    // Team color header
    const headerH = 140;
    const headerGrad = ctx.createLinearGradient(0, 0, W, headerH);
    headerGrad.addColorStop(0, team.color || '#10b981');
    headerGrad.addColorStop(1, 'rgba(0,0,0,0.3)');
    ctx.fillStyle = headerGrad;
    ctx.fillRect(0, 0, W, headerH);

    // Team avatar
    ctx.beginPath();
    ctx.arc(W / 2, 55, 30, 0, Math.PI * 2);
    ctx.fillStyle = 'rgba(255,255,255,0.2)';
    ctx.fill();
    ctx.fillStyle = '#fff';
    ctx.font = '700 20px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText((team.shortName || team.name.substring(0, 3)).toUpperCase(), W / 2, 55);
    ctx.textBaseline = 'alphabetic';

    ctx.fillStyle = '#fff';
    ctx.font = '700 24px Outfit, sans-serif';
    ctx.fillText(team.name, W / 2, 115);

    // Tournament name
    ctx.fillStyle = 'rgba(255,255,255,0.6)';
    ctx.font = '400 12px Inter, sans-serif';
    ctx.fillText(tournament.name || 'CrickDesk Tournament', W / 2, 135);

    // Player list
    const startY = 170;
    const rowH = 50;

    const roleOrder = { 'wicket-keeper': 0, 'batsman': 1, 'all-rounder': 2, 'bowler': 3 };
    const sortedPlayers = [...players].sort((a, b) => {
      if (a.id === team.captainId) return -1;
      if (b.id === team.captainId) return 1;
      return (roleOrder[a.role] || 4) - (roleOrder[b.role] || 4);
    });

    sortedPlayers.forEach((p, i) => {
      const y = startY + i * rowH;
      const isCaptain = p.id === team.captainId;

      if (i % 2 === 0) {
        ctx.fillStyle = 'rgba(255,255,255,0.02)';
        ctx.fillRect(20, y, W - 40, rowH);
      }

      // Index
      ctx.fillStyle = '#6b7280';
      ctx.font = '400 12px Inter, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(i + 1, 45, y + 30);

      // Name
      ctx.fillStyle = isCaptain ? '#fbbf24' : '#f9fafb';
      ctx.font = (isCaptain ? '700' : '500') + ' 14px Inter, sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText(p.name + (isCaptain ? ' (C)' : ''), 75, y + 28);

      // Role badge
      const roleColors = { 'batsman': '#10b981', 'bowler': '#ef4444', 'all-rounder': '#8b5cf6', 'wicket-keeper': '#3b82f6' };
      const roleLabels = { 'batsman': 'BAT', 'bowler': 'BOWL', 'all-rounder': 'AR', 'wicket-keeper': 'WK' };
      const rc = roleColors[p.role] || '#6b7280';
      const rl = roleLabels[p.role] || p.role;

      roundRect(ctx, W - 90, y + 15, 55, 22, 6);
      ctx.fillStyle = rc + '33';
      ctx.fill();
      ctx.fillStyle = rc;
      ctx.font = '600 10px Inter, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(rl, W - 62, y + 30);

      // Batting style
      ctx.fillStyle = '#6b7280';
      ctx.font = '400 11px Inter, sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText(p.battingStyle === 'left' ? 'Left-hand' : 'Right-hand', 75, y + 44);
    });

    drawBrandFooter(ctx, W, H);

    const preview = document.getElementById('share-preview-squad');
    if (preview) {
      preview.innerHTML = '';
      const img = document.createElement('img');
      img.src = canvas.toDataURL();
      img.style.cssText = 'width:100%;border-radius:8px;';
      preview.appendChild(img);
    }

    return canvas;
  }

  // ══════════════════════════════════════════════════════════════════════
  //  GENERATE: Player Profile Card
  // ══════════════════════════════════════════════════════════════════════

  function generatePlayerProfile(playerId) {
    const player = Data().getPlayer(playerId);
    if (!player) return null;
    const team = Data().getTeam(player.teamId);
    const matches = Data().getMatches().filter(m => m.status === 'completed');

    // Calculate stats
    let batInnings = 0, runs = 0, balls = 0, fours = 0, sixes = 0, highScore = 0, notOuts = 0;
    let bowlInnings = 0, wickets = 0, bowlRuns = 0, bowlBalls = 0, bowlMaidens = 0;
    let matchCount = 0;
    const matchSet = new Set();

    matches.forEach(m => {
      if (!m.innings) return;
      let inThisMatch = false;
      m.innings.forEach(inn => {
        if (inn.battingScorecard) {
          inn.battingScorecard.forEach(e => {
            if (e.playerId === playerId) {
              inThisMatch = true;
              batInnings++;
              runs += e.runs || 0;
              balls += e.balls || 0;
              fours += e.fours || 0;
              sixes += e.sixes || 0;
              if ((e.runs || 0) > highScore) highScore = e.runs;
              if (!e.howOut || e.howOut === 'not out' || e.howOut === 'Not Out') notOuts++;
            }
          });
        }
        if (inn.bowlingScorecard) {
          inn.bowlingScorecard.forEach(e => {
            if (e.playerId === playerId) {
              inThisMatch = true;
              bowlInnings++;
              wickets += e.wickets || 0;
              bowlRuns += e.runs || 0;
              const bpo = Data().getTournament().ballsPerOver || 6;
              bowlBalls += e.overs ? Math.floor(e.overs) * bpo + Math.round((e.overs % 1) * 10) : (e.balls || 0);
              bowlMaidens += e.maidens || 0;
            }
          });
        }
      });
      if (inThisMatch && !matchSet.has(m.id)) { matchSet.add(m.id); matchCount++; }
    });

    const canvas = document.createElement('canvas');
    const W = 600, H = 800;
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext('2d');

    drawDarkBg(ctx, W, H);

    // Team color accent
    ctx.fillStyle = team ? team.color : '#10b981';
    ctx.fillRect(0, 0, W, 5);

    // Avatar circle
    const avatarY = 100;
    ctx.beginPath();
    ctx.arc(W / 2, avatarY, 50, 0, Math.PI * 2);
    ctx.fillStyle = team ? team.color : '#374151';
    ctx.fill();
    ctx.fillStyle = '#fff';
    ctx.font = '700 28px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(Utils().getPlayerInitials(player.name), W / 2, avatarY);
    ctx.textBaseline = 'alphabetic';

    // Name
    ctx.fillStyle = '#f9fafb';
    ctx.font = '700 26px Outfit, sans-serif';
    ctx.fillText(player.name, W / 2, 175);

    // Team + role
    ctx.fillStyle = '#9ca3af';
    ctx.font = '400 14px Inter, sans-serif';
    ctx.fillText(`${team ? team.name : ''} • ${player.role}`, W / 2, 200);

    // Batting style
    ctx.fillStyle = '#6b7280';
    ctx.font = '400 12px Inter, sans-serif';
    ctx.fillText(`${player.battingStyle === 'left' ? 'Left' : 'Right'}-hand bat${player.bowlingStyle ? ' • ' + player.bowlingStyle : ''}`, W / 2, 222);

    // Divider
    ctx.strokeStyle = 'rgba(255,255,255,0.08)';
    ctx.beginPath();
    ctx.moveTo(50, 250);
    ctx.lineTo(W - 50, 250);
    ctx.stroke();

    // Batting Stats
    ctx.fillStyle = '#f9fafb';
    ctx.font = '600 16px Outfit, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('🏏 Batting', W / 2, 285);

    const bpo = Data().getTournament().ballsPerOver || 6;
    const sr = balls > 0 ? ((runs / balls) * 100).toFixed(1) : '0.0';
    const avg = (batInnings - notOuts) > 0 ? (runs / (batInnings - notOuts)).toFixed(2) : runs > 0 ? runs.toFixed(2) : '0.00';

    const batStats = [
      { label: 'Mat', value: matchCount },
      { label: 'Runs', value: runs },
      { label: 'HS', value: highScore },
      { label: 'Avg', value: avg },
      { label: 'SR', value: sr },
      { label: '4s', value: fours },
      { label: '6s', value: sixes }
    ];

    const statW = 70;
    const statStartX = (W - batStats.length * statW) / 2;
    batStats.forEach((s, i) => {
      const x = statStartX + i * statW + statW / 2;
      ctx.fillStyle = '#f9fafb';
      ctx.font = '700 20px Outfit, sans-serif';
      ctx.fillText(s.value, x, 325);
      ctx.fillStyle = '#6b7280';
      ctx.font = '400 11px Inter, sans-serif';
      ctx.fillText(s.label, x, 342);
    });

    // Bowling Stats
    ctx.fillStyle = '#f9fafb';
    ctx.font = '600 16px Outfit, sans-serif';
    ctx.fillText('🎯 Bowling', W / 2, 400);

    const overs = Utils().formatOvers(bowlBalls, bpo);
    const bowlAvg = wickets > 0 ? (bowlRuns / wickets).toFixed(2) : '—';
    const econ = Utils().calculateEconomy(bowlRuns, bowlBalls, bpo);

    const bowlStats = [
      { label: 'Overs', value: overs },
      { label: 'Wkts', value: wickets },
      { label: 'Runs', value: bowlRuns },
      { label: 'Avg', value: bowlAvg },
      { label: 'Econ', value: econ },
      { label: 'Mdn', value: bowlMaidens }
    ];

    const bowlStatW = 80;
    const bowlStartX = (W - bowlStats.length * bowlStatW) / 2;
    bowlStats.forEach((s, i) => {
      const x = bowlStartX + i * bowlStatW + bowlStatW / 2;
      ctx.fillStyle = '#f9fafb';
      ctx.font = '700 20px Outfit, sans-serif';
      ctx.fillText(s.value, x, 440);
      ctx.fillStyle = '#6b7280';
      ctx.font = '400 11px Inter, sans-serif';
      ctx.fillText(s.label, x, 457);
    });

    drawBrandFooter(ctx, W, H);

    const preview = document.getElementById('share-preview-player');
    if (preview) {
      preview.innerHTML = '';
      const img = document.createElement('img');
      img.src = canvas.toDataURL();
      img.style.cssText = 'width:100%;border-radius:8px;';
      preview.appendChild(img);
    }

    return canvas;
  }

  // ══════════════════════════════════════════════════════════════════════
  //  EXPORT / IMPORT FUNCTIONS
  // ══════════════════════════════════════════════════════════════════════

  function exportJSON() {
    const jsonStr = Data().exportJSON();
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const link = document.createElement('a');
    const date = new Date().toISOString().slice(0, 10);
    link.download = `crickdesk_backup_${date}.json`;
    link.href = URL.createObjectURL(blob);
    link.click();
    URL.revokeObjectURL(link.href);
    Utils().showToast('Data exported successfully!', 'success');
  }

  function importJSON(file) {
    const reader = new FileReader();
    reader.onload = function (e) {
      try {
        const result = Data().importJSON(e.target.result);
        if (result === false) {
          Utils().showToast('Invalid data file.', 'error');
          return;
        }
        Utils().showToast('Data imported successfully! Reloading...', 'success');
        setTimeout(() => location.reload(), 1500);
      } catch (err) {
        Utils().showToast('Import failed: ' + err.message, 'error');
      }
    };
    reader.readAsText(file);
  }

  function exportCSV() {
    const matches = Data().getMatches().filter(m => m.status === 'completed');
    const players = Data().getPlayers();
    const map = {};

    players.forEach(p => {
      map[p.id] = {
        name: p.name,
        team: (Data().getTeam(p.teamId) || {}).name || '',
        role: p.role,
        matches: 0,
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        wickets: 0,
        bowlRuns: 0,
        bowlBalls: 0,
        catches: 0,
        matchSet: new Set()
      };
    });

    matches.forEach(m => {
      if (!m.innings) return;
      m.innings.forEach(inn => {
        if (inn.battingScorecard) {
          inn.battingScorecard.forEach(e => {
            const s = map[e.playerId];
            if (!s) return;
            if (!s.matchSet.has(m.id)) { s.matchSet.add(m.id); s.matches++; }
            s.runs += e.runs || 0;
            s.balls += e.balls || 0;
            s.fours += e.fours || 0;
            s.sixes += e.sixes || 0;
          });
        }
        if (inn.bowlingScorecard) {
          inn.bowlingScorecard.forEach(e => {
            const s = map[e.playerId];
            if (!s) return;
            if (!s.matchSet.has(m.id)) { s.matchSet.add(m.id); s.matches++; }
            s.wickets += e.wickets || 0;
            s.bowlRuns += e.runs || 0;
            const bpo = Data().getTournament().ballsPerOver || 6;
            s.bowlBalls += e.overs ? Math.floor(e.overs) * bpo + Math.round((e.overs % 1) * 10) : (e.balls || 0);
          });
        }
        if (inn.balls) {
          inn.balls.forEach(ball => {
            if (ball.wicket && ball.wicket.type === 'caught' && ball.wicket.fielderId && map[ball.wicket.fielderId]) {
              map[ball.wicket.fielderId].catches++;
            }
          });
        }
      });
    });

    const bpo = Data().getTournament().ballsPerOver || 6;
    let csv = 'Name,Team,Role,Matches,Runs,Balls,SR,4s,6s,Wickets,Bowl Runs,Bowl Overs,Econ,Catches\n';
    Object.values(map).filter(s => s.matches > 0).forEach(s => {
      const sr = s.balls > 0 ? ((s.runs / s.balls) * 100).toFixed(1) : '0.0';
      const overs = Utils().formatOvers(s.bowlBalls, bpo);
      const econ = Utils().calculateEconomy(s.bowlRuns, s.bowlBalls, bpo);
      csv += `"${s.name}","${s.team}","${s.role}",${s.matches},${s.runs},${s.balls},${sr},${s.fours},${s.sixes},${s.wickets},${s.bowlRuns},"${overs}",${econ},${s.catches}\n`;
    });

    const blob = new Blob([csv], { type: 'text/csv' });
    const link = document.createElement('a');
    link.download = 'crickdesk_stats.csv';
    link.href = URL.createObjectURL(blob);
    link.click();
    URL.revokeObjectURL(link.href);
    Utils().showToast('Stats exported as CSV!', 'success');
  }

  // ══════════════════════════════════════════════════════════════════════
  //  GENERATE: Match PDF Report (printable HTML)
  // ══════════════════════════════════════════════════════════════════════

  function generateMatchReport(matchId) {
    const match = Data().getMatch(matchId);
    if (!match) return;
    const t1 = Data().getTeam(match.team1Id);
    const t2 = Data().getTeam(match.team2Id);
    const tournament = Data().getTournament();
    const bpo = tournament.ballsPerOver || 6;

    let inningsHtml = '';
    if (match.innings) {
      match.innings.forEach((inn, idx) => {
        const battingTeam = Data().getTeam(inn.battingTeamId);
        const bowlingTeam = Data().getTeam(inn.bowlingTeamId);
        const overs = Utils().formatOvers(inn.totalBalls || 0, bpo);

        // Batting scorecard
        let batRows = '';
        if (inn.battingScorecard) {
          inn.battingScorecard.forEach(e => {
            const p = Data().getPlayer(e.playerId);
            const bowler = e.bowlerId ? Data().getPlayer(e.bowlerId) : null;
            const fielder = e.fielderId ? Data().getPlayer(e.fielderId) : null;
            let howOut = e.howOut || 'not out';
            if (howOut !== 'not out' && howOut !== 'Not Out') {
              if (bowler) howOut += ` b ${bowler.name}`;
              if (fielder) howOut = `c ${fielder.name} ` + howOut;
            }
            const sr = e.balls > 0 ? ((e.runs / e.balls) * 100).toFixed(1) : '0.0';
            batRows += `<tr>
              <td style="font-weight:600;">${p ? p.name : 'Unknown'}</td>
              <td style="font-size:12px;color:#666;">${howOut}</td>
              <td style="font-weight:700;">${e.runs || 0}</td>
              <td>${e.balls || 0}</td>
              <td>${e.fours || 0}</td>
              <td>${e.sixes || 0}</td>
              <td>${sr}</td>
            </tr>`;
          });
        }

        // Bowling scorecard
        let bowlRows = '';
        if (inn.bowlingScorecard) {
          inn.bowlingScorecard.forEach(e => {
            const p = Data().getPlayer(e.playerId);
            const ov = e.overs || Utils().formatOvers(e.balls || 0, bpo);
            const econ = Utils().calculateEconomy(e.runs || 0, e.overs ? Math.floor(e.overs) * bpo + Math.round((e.overs % 1) * 10) : (e.balls || 0), bpo);
            bowlRows += `<tr>
              <td style="font-weight:600;">${p ? p.name : 'Unknown'}</td>
              <td>${ov}</td>
              <td>${e.maidens || 0}</td>
              <td>${e.runs || 0}</td>
              <td style="font-weight:700;">${e.wickets || 0}</td>
              <td>${e.wides || 0}</td>
              <td>${e.noBalls || 0}</td>
              <td>${econ}</td>
            </tr>`;
          });
        }

        // Fall of wickets
        let fowStr = '';
        if (inn.fallOfWickets && inn.fallOfWickets.length > 0) {
          fowStr = inn.fallOfWickets.map(f => {
            const p = Data().getPlayer(f.playerId);
            return `${f.wicketNumber}-${f.runs} (${p ? p.name : '?'}, ${f.overs || ''} ov)`;
          }).join(', ');
        }

        // Partnerships
        let partHtml = '';
        if (inn.partnerships && inn.partnerships.length > 0) {
          partHtml = '<h4>Partnerships</h4><table class="report-table"><thead><tr><th>Bat 1</th><th>Bat 2</th><th>Runs</th><th>Balls</th></tr></thead><tbody>';
          inn.partnerships.forEach(p => {
            const b1 = Data().getPlayer(p.bat1Id);
            const b2 = Data().getPlayer(p.bat2Id);
            partHtml += `<tr><td>${b1 ? b1.name : '?'}</td><td>${b2 ? b2.name : '?'}</td><td>${p.runs}</td><td>${p.balls}</td></tr>`;
          });
          partHtml += '</tbody></table>';
        }

        // Extras
        const extras = inn.extras || {};
        const extrasStr = `Wides: ${extras.wides || 0}, NB: ${extras.noBalls || 0}, Byes: ${extras.byes || 0}, LB: ${extras.legByes || 0}`;
        const totalExtras = (extras.wides || 0) + (extras.noBalls || 0) + (extras.byes || 0) + (extras.legByes || 0);

        inningsHtml += `
          <div class="innings-section">
            <h3>${battingTeam ? battingTeam.name : 'Unknown'} Innings - ${inn.totalRuns || 0}/${inn.totalWickets || 0} (${overs} ov)</h3>
            <table class="report-table">
              <thead><tr><th>Batter</th><th>How Out</th><th>R</th><th>B</th><th>4s</th><th>6s</th><th>SR</th></tr></thead>
              <tbody>${batRows}</tbody>
              <tfoot><tr><td colspan="2"><strong>Extras:</strong> ${extrasStr} = ${totalExtras}</td><td colspan="5"><strong>Total: ${inn.totalRuns || 0}/${inn.totalWickets || 0}</strong></td></tr></tfoot>
            </table>
            ${fowStr ? `<p class="fow"><strong>Fall of Wickets:</strong> ${fowStr}</p>` : ''}
            <h4>Bowling</h4>
            <table class="report-table">
              <thead><tr><th>Bowler</th><th>O</th><th>M</th><th>R</th><th>W</th><th>Wd</th><th>NB</th><th>Econ</th></tr></thead>
              <tbody>${bowlRows}</tbody>
            </table>
            ${partHtml}
          </div>
        `;
      });
    }

    // Commentary log
    let commentaryHtml = '';
    if (match.commentary && match.commentary.length > 0) {
      commentaryHtml = '<div class="commentary-section"><h3>Commentary Log</h3><div class="commentary-list">';
      match.commentary.forEach(c => {
        commentaryHtml += `<div class="comm-entry"><span class="comm-over">${c.over}.${c.ball}</span> <span>${c.text}</span></div>`;
      });
      commentaryHtml += '</div></div>';
    }

    const mom = match.manOfMatch ? Data().getPlayer(match.manOfMatch) : null;

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Match Report - ${t1 ? t1.name : ''} vs ${t2 ? t2.name : ''}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Outfit:wght@400;500;600;700;800&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Inter', sans-serif; background: #fff; color: #1a1a1a; padding: 30px; max-width: 900px; margin: 0 auto; }
  h1 { font-family: 'Outfit', sans-serif; font-size: 24px; margin-bottom: 4px; }
  h2 { font-family: 'Outfit', sans-serif; font-size: 18px; color: #333; margin-bottom: 10px; }
  h3 { font-family: 'Outfit', sans-serif; font-size: 16px; margin: 20px 0 10px; padding-bottom: 6px; border-bottom: 2px solid #10b981; }
  h4 { font-size: 14px; margin: 16px 0 8px; color: #555; }
  .report-header { text-align: center; margin-bottom: 20px; padding-bottom: 16px; border-bottom: 1px solid #e5e7eb; }
  .result { font-size: 16px; color: #10b981; font-weight: 600; margin: 8px 0; }
  .meta { font-size: 13px; color: #666; }
  .mom { font-size: 14px; color: #b8860b; margin: 6px 0; }
  .report-table { width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 13px; }
  .report-table th { background: #f3f4f6; padding: 8px 10px; text-align: left; font-weight: 600; border-bottom: 2px solid #d1d5db; }
  .report-table td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; }
  .report-table tfoot td { font-weight: 500; border-top: 2px solid #d1d5db; background: #f9fafb; }
  .fow { font-size: 12px; color: #555; margin: 8px 0 16px; }
  .innings-section { margin-bottom: 30px; }
  .commentary-section { margin-top: 30px; }
  .commentary-list { max-height: 400px; overflow-y: auto; }
  .comm-entry { padding: 4px 0; font-size: 12px; border-bottom: 1px solid #f3f4f6; }
  .comm-over { font-weight: 700; color: #10b981; margin-right: 8px; display: inline-block; min-width: 35px; }
  @media print {
    body { padding: 15px; font-size: 11px; }
    .report-table { font-size: 11px; }
    .report-table th { background: #eee !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    h3 { border-bottom-color: #333; }
    .commentary-list { max-height: none; }
    .no-print { display: none; }
  }
</style>
</head>
<body>
  <button class="no-print" onclick="window.print()" style="position:fixed;top:10px;right:10px;padding:8px 20px;background:#10b981;color:#fff;border:none;border-radius:6px;cursor:pointer;font-weight:600;">🖨️ Print</button>
  <div class="report-header">
    <p class="meta">${tournament.name || 'CrickDesk Tournament'}</p>
    <h1>${t1 ? t1.name : 'Team 1'} vs ${t2 ? t2.name : 'Team 2'}</h1>
    <p class="result">${match.result || ''}</p>
    ${mom ? `<p class="mom">⭐ Man of the Match: ${mom.name}</p>` : ''}
    <p class="meta">${match.date ? Utils().formatDate(match.date) : ''} ${match.venue ? '• ' + match.venue : ''}</p>
    ${match.tossWonBy ? `<p class="meta">Toss: ${(Data().getTeam(match.tossWonBy) || {}).name || '?'} won, chose to ${match.tossDecision || '?'}</p>` : ''}
  </div>
  ${inningsHtml}
  ${commentaryHtml}
</body>
</html>`;

    const win = window.open('', '_blank');
    if (win) {
      win.document.write(html);
      win.document.close();
    } else {
      Utils().showToast('Pop-up blocked. Please allow pop-ups.', 'error');
    }
  }

  // ══════════════════════════════════════════════════════════════════════
  //  MAIN RENDER
  // ══════════════════════════════════════════════════════════════════════

  function render() {
    const completedMatches = Data().getMatchesByStatus('completed');
    const matchOpts = completedMatches.map(m => {
      const t1 = Data().getTeam(m.team1Id);
      const t2 = Data().getTeam(m.team2Id);
      return `<option value="${m.id}">${t1 ? t1.name : 'Team ?'} vs ${t2 ? t2.name : 'Team ?'} ${m.date ? '(' + Utils().formatDate(m.date) + ')' : ''}</option>`;
    }).join('');

    const teams = Data().getTeams();
    const teamOpts = teams.map(t => `<option value="${t.id}">${t.name}</option>`).join('');

    const allPlayers = Data().getPlayers();
    const playerOpts = allPlayers.map(p => {
      const t = Data().getTeam(p.teamId);
      return `<option value="${p.id}">${p.name} (${t ? t.shortName : '?'})</option>`;
    }).join('');

    return `
      <div class="page-header">
        <div>
          <h1 style="font-family:var(--font-heading);font-size:28px;font-weight:700;color:var(--text-primary);">📤 Share & Export</h1>
          <p class="section-subtitle" style="margin-top:4px;">Generate shareable images and manage data</p>
        </div>
      </div>
      <div class="page-content">

        <h2 class="section-title" style="margin-bottom:16px;">🖼️ Share Cards</h2>
        <div class="bento-grid grid-3" style="gap:16px;margin-bottom:32px;">

          <!-- Points Table -->
          <div class="card glass" style="padding:20px;">
            <h3 style="font-family:var(--font-heading);font-size:16px;margin-bottom:12px;color:var(--text-primary);">📊 Points Table</h3>
            <div id="share-preview-points" style="min-height:100px;background:var(--bg-input);border-radius:var(--radius-sm);margin-bottom:12px;display:flex;align-items:center;justify-content:center;overflow:hidden;">
              <span style="color:var(--text-muted);font-size:13px;">Click Generate to preview</span>
            </div>
            <div style="display:flex;gap:8px;">
              <button class="btn btn-primary btn-sm" id="share-gen-points">Generate</button>
              <button class="btn btn-secondary btn-sm" id="share-dl-points" disabled>Download</button>
            </div>
          </div>

          <!-- Match Summary -->
          <div class="card glass" style="padding:20px;">
            <h3 style="font-family:var(--font-heading);font-size:16px;margin-bottom:12px;color:var(--text-primary);">🏏 Match Summary</h3>
            <div class="form-group" style="margin-bottom:8px;">
              <select class="form-select" id="share-match-select">
                <option value="">Select a match</option>
                ${matchOpts}
              </select>
            </div>
            <div id="share-preview-match" style="min-height:100px;background:var(--bg-input);border-radius:var(--radius-sm);margin-bottom:12px;display:flex;align-items:center;justify-content:center;overflow:hidden;">
              <span style="color:var(--text-muted);font-size:13px;">Select a match & generate</span>
            </div>
            <div style="display:flex;gap:8px;">
              <button class="btn btn-primary btn-sm" id="share-gen-match">Generate</button>
              <button class="btn btn-secondary btn-sm" id="share-dl-match" disabled>Download</button>
            </div>
          </div>

          <!-- Fixtures -->
          <div class="card glass" style="padding:20px;">
            <h3 style="font-family:var(--font-heading);font-size:16px;margin-bottom:12px;color:var(--text-primary);">📅 Fixtures</h3>
            <div id="share-preview-fixtures" style="min-height:100px;background:var(--bg-input);border-radius:var(--radius-sm);margin-bottom:12px;display:flex;align-items:center;justify-content:center;overflow:hidden;">
              <span style="color:var(--text-muted);font-size:13px;">Click Generate to preview</span>
            </div>
            <div style="display:flex;gap:8px;">
              <button class="btn btn-primary btn-sm" id="share-gen-fixtures">Generate</button>
              <button class="btn btn-secondary btn-sm" id="share-dl-fixtures" disabled>Download</button>
            </div>
          </div>

          <!-- Team Squad -->
          <div class="card glass" style="padding:20px;">
            <h3 style="font-family:var(--font-heading);font-size:16px;margin-bottom:12px;color:var(--text-primary);">👥 Team Squad</h3>
            <div class="form-group" style="margin-bottom:8px;">
              <select class="form-select" id="share-team-select">
                <option value="">Select a team</option>
                ${teamOpts}
              </select>
            </div>
            <div id="share-preview-squad" style="min-height:100px;background:var(--bg-input);border-radius:var(--radius-sm);margin-bottom:12px;display:flex;align-items:center;justify-content:center;overflow:hidden;">
              <span style="color:var(--text-muted);font-size:13px;">Select a team & generate</span>
            </div>
            <div style="display:flex;gap:8px;">
              <button class="btn btn-primary btn-sm" id="share-gen-squad">Generate</button>
              <button class="btn btn-secondary btn-sm" id="share-dl-squad" disabled>Download</button>
            </div>
          </div>

          <!-- Player Profile -->
          <div class="card glass" style="padding:20px;">
            <h3 style="font-family:var(--font-heading);font-size:16px;margin-bottom:12px;color:var(--text-primary);">🏅 Player Profile</h3>
            <div class="form-group" style="margin-bottom:8px;">
              <select class="form-select" id="share-player-select">
                <option value="">Select a player</option>
                ${playerOpts}
              </select>
            </div>
            <div id="share-preview-player" style="min-height:100px;background:var(--bg-input);border-radius:var(--radius-sm);margin-bottom:12px;display:flex;align-items:center;justify-content:center;overflow:hidden;">
              <span style="color:var(--text-muted);font-size:13px;">Select a player & generate</span>
            </div>
            <div style="display:flex;gap:8px;">
              <button class="btn btn-primary btn-sm" id="share-gen-player">Generate</button>
              <button class="btn btn-secondary btn-sm" id="share-dl-player" disabled>Download</button>
            </div>
          </div>

        </div>

        <div class="divider" style="margin:32px 0;border-top:1px solid var(--border-color);"></div>

        <h2 class="section-title" style="margin-bottom:16px;">💾 Export & Import</h2>
        <div class="bento-grid grid-3" style="gap:16px;margin-bottom:24px;">
          <div class="card glass" style="padding:20px;text-align:center;">
            <div style="font-size:32px;margin-bottom:8px;">📦</div>
            <h3 style="font-family:var(--font-heading);font-size:15px;margin-bottom:8px;color:var(--text-primary);">Export All Data</h3>
            <p style="font-size:12px;color:var(--text-muted);margin-bottom:12px;">Download full tournament data as JSON backup</p>
            <button class="btn btn-primary" id="share-export-json">Export JSON</button>
          </div>

          <div class="card glass" style="padding:20px;text-align:center;">
            <div style="font-size:32px;margin-bottom:8px;">📥</div>
            <h3 style="font-family:var(--font-heading);font-size:15px;margin-bottom:8px;color:var(--text-primary);">Import Data</h3>
            <p style="font-size:12px;color:var(--accent-amber);margin-bottom:12px;">⚠️ This will overwrite existing data</p>
            <input type="file" accept=".json" id="share-import-file" style="display:none;">
            <button class="btn btn-secondary" id="share-import-btn">Import JSON</button>
          </div>

          <div class="card glass" style="padding:20px;text-align:center;">
            <div style="font-size:32px;margin-bottom:8px;">📊</div>
            <h3 style="font-family:var(--font-heading);font-size:15px;margin-bottom:8px;color:var(--text-primary);">Export Stats (CSV)</h3>
            <p style="font-size:12px;color:var(--text-muted);margin-bottom:12px;">Download player statistics as spreadsheet</p>
            <button class="btn btn-primary" id="share-export-csv">Export CSV</button>
          </div>
        </div>

        <div class="divider" style="margin:32px 0;border-top:1px solid var(--border-color);"></div>

        <h2 class="section-title" style="margin-bottom:16px;">🖨️ Match Report</h2>
        <div class="card glass" style="padding:20px;">
          <div class="form-row" style="gap:12px;align-items:flex-end;">
            <div class="form-group" style="flex:1;">
              <label class="form-label">Select Completed Match</label>
              <select class="form-select" id="share-report-match">
                <option value="">Select a match</option>
                ${matchOpts}
              </select>
            </div>
            <button class="btn btn-primary" id="share-gen-report" style="flex-shrink:0;">Generate Report</button>
          </div>
          <p style="font-size:12px;color:var(--text-muted);margin-top:8px;">Opens a print-ready scorecard in a new tab with full innings details, fall of wickets, partnerships, and commentary.</p>
        </div>

      </div>
    `;
  }

  // ══════════════════════════════════════════════════════════════════════
  //  ATTACH EVENTS
  // ══════════════════════════════════════════════════════════════════════

  function attachEvents() {
    const container = document.getElementById('page-share');
    if (!container || container.dataset.eventsAttached) return;
    container.dataset.eventsAttached = 'true';

    // Store generated canvases
    const canvases = {};

    container.addEventListener('click', e => {
      const target = e.target;

      // Points Table
      if (target.id === 'share-gen-points') {
        canvases.points = generatePointsTable();
        const dlBtn = document.getElementById('share-dl-points');
        if (dlBtn && canvases.points) dlBtn.disabled = false;
        Utils().showToast('Points table generated!', 'success');
      }
      if (target.id === 'share-dl-points' && canvases.points) {
        downloadCanvas(canvases.points, 'crickdesk_points_table.png');
      }

      // Match Summary
      if (target.id === 'share-gen-match') {
        const matchId = document.getElementById('share-match-select').value;
        if (!matchId) { Utils().showToast('Please select a match', 'error'); return; }
        canvases.match = generateMatchSummary(matchId);
        const dlBtn = document.getElementById('share-dl-match');
        if (dlBtn && canvases.match) dlBtn.disabled = false;
        Utils().showToast('Match summary generated!', 'success');
      }
      if (target.id === 'share-dl-match' && canvases.match) {
        downloadCanvas(canvases.match, 'crickdesk_match_summary.png');
      }

      // Fixtures
      if (target.id === 'share-gen-fixtures') {
        canvases.fixtures = generateFixtures();
        const dlBtn = document.getElementById('share-dl-fixtures');
        if (dlBtn && canvases.fixtures) dlBtn.disabled = false;
        Utils().showToast('Fixtures image generated!', 'success');
      }
      if (target.id === 'share-dl-fixtures' && canvases.fixtures) {
        downloadCanvas(canvases.fixtures, 'crickdesk_fixtures.png');
      }

      // Team Squad
      if (target.id === 'share-gen-squad') {
        const teamId = document.getElementById('share-team-select').value;
        if (!teamId) { Utils().showToast('Please select a team', 'error'); return; }
        canvases.squad = generateTeamSquad(teamId);
        const dlBtn = document.getElementById('share-dl-squad');
        if (dlBtn && canvases.squad) dlBtn.disabled = false;
        Utils().showToast('Team squad card generated!', 'success');
      }
      if (target.id === 'share-dl-squad' && canvases.squad) {
        downloadCanvas(canvases.squad, 'crickdesk_team_squad.png');
      }

      // Player Profile
      if (target.id === 'share-gen-player') {
        const playerId = document.getElementById('share-player-select').value;
        if (!playerId) { Utils().showToast('Please select a player', 'error'); return; }
        canvases.player = generatePlayerProfile(playerId);
        const dlBtn = document.getElementById('share-dl-player');
        if (dlBtn && canvases.player) dlBtn.disabled = false;
        Utils().showToast('Player profile card generated!', 'success');
      }
      if (target.id === 'share-dl-player' && canvases.player) {
        downloadCanvas(canvases.player, 'crickdesk_player_profile.png');
      }

      // Export JSON
      if (target.id === 'share-export-json') {
        exportJSON();
      }

      // Import
      if (target.id === 'share-import-btn') {
        const fileInput = document.getElementById('share-import-file');
        if (fileInput) fileInput.click();
      }

      // Export CSV
      if (target.id === 'share-export-csv') {
        exportCSV();
      }

      // Match Report
      if (target.id === 'share-gen-report') {
        const matchId = document.getElementById('share-report-match').value;
        if (!matchId) { Utils().showToast('Please select a match', 'error'); return; }
        generateMatchReport(matchId);
      }
    });

    container.addEventListener('change', e => {
      if (e.target.id === 'share-import-file') {
        const file = e.target.files[0];
        if (file) {
          Utils().confirmDialog('Importing data will overwrite ALL existing data. Are you sure?').then(ok => {
            if (ok) importJSON(file);
          });
        }
      }
    });
  }

  // ══════════════════════════════════════════════════════════════════════
  //  PUBLIC API
  // ══════════════════════════════════════════════════════════════════════

  return {
    init() {
      const container = document.getElementById('page-share');
      if (!container) return;
      container.innerHTML = render();
      this.attachEvents();
    },
    render,
    attachEvents
  };
})();
